---
title: ''
author: "Torredemer"
date: "2026-05-25"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(car)
library(readr)



dd <- read.csv("C:/Users/Paco/Documents/TFM/bases_de_datos/DB_ea_sports24_afterprocessing.csv", sep=";")
for (i in 1:ncol(dd)) {
  if (is.character(dd[, i])) {
    dd[, i] <- as.factor(dd[, i])
  }
}
names(dd)
dim(dd)
summary(dd)


sapply(dd, class)
```


```{r}
names(dd)

dcon <- data.frame (dd$overall, dd$attack, dd$midfield, dd$defence, dd$def_team_width, dd$def_team_depth, dd$off_team_width, dd$off_players_in_box)
dim(dcon)

```


```{r}
library(cluster)
d  <- dist(dcon[1:658,])
#excluimos el nombre del equipo y su estadio pues no son relevantes
actives <- c(2:8, 10:16) 
dissimMatrix <- daisy(dd[,actives], metric = "gower", stand=TRUE)

distMatrix<-dissimMatrix^2

h1 <- hclust(distMatrix,method="ward.D")

plot(h1)

```

```{r}
nc = 3

c3 <- cutree(h1,nc)



nc = 4

c4 <- cutree(h1,nc)



table(c3)
table(c4)
table(c3,c4)



```
```{r}
names(dd)

#overall
boxplot(dd[,5]~c3, horizontal=TRUE)

#defence
boxplot(dd[,8]~c3, horizontal=TRUE)

#midfield
boxplot(dd[,7]~c3, horizontal=TRUE)

#attack
boxplot(dd[,6]~c3, horizontal=TRUE)


pairs(dcon[,1:8], col=c3)

c3 <- as.factor(c3)

plot(dd$overall, dd$defence,col=c3,main="Clustering defence in 3 classes")
legend("topright",levels(c3),pch=1,col=c(1:5), cex=0.6)

plot(dd$overall, dd$midfield,col=c3,main="Clustering midfield in 3 classes")
legend("topright",levels(c3),pch=1,col=c(1:5), cex=0.6)

plot(dd$overall, dd$attack,col=c3,main="Clustering attack in 3 classes")
legend("topright",levels(c3),pch=1,col=c(1:5), cex=0.6)
```


```{r}
cdg <- aggregate(as.data.frame(dcon),list(c3),mean)
cdg


```

```{r}
# clusters como factor
c3 <- as.factor(c3)

# recorrer todas las variables
for(v in names(dd)){

  cat("\n====================================\n")
  cat("VARIABLE:", v, "\n")

  # -------------------------------------------------
  # VARIABLES NUMÉRICAS
  # -------------------------------------------------
  if(is.numeric(dd[[v]])){

    cat("\nEstadísticos por grupos:\n")

    for(g in levels(c3)){

      cat("\nGrupo", g, "\n")

      print(summary(dd[c3 == g, v]))
    }

    # boxplot
    boxplot(dd[[v]] ~ c3,
            horizontal = TRUE,
            main = paste(v, "por cluster"),
            col = "lightblue")
  }

  # -------------------------------------------------
  # VARIABLES CATEGÓRICAS / FACTOR / BINARIAS
  # -------------------------------------------------
  else if(is.factor(dd[[v]]) || 
          is.character(dd[[v]]) || 
          is.logical(dd[[v]])){

    # convertir a factor
    var_cat <- as.factor(dd[[v]])

    # cross table
    tabla <- table(var_cat, c3)

    cat("\nCross Table:\n")
    print(tabla)

    # proporciones por cluster
    prop <- prop.table(tabla, 2)

    # gráfico de líneas
    matplot(t(prop),
            type = "l",
            lty = 1,
            lwd = 2,
            xaxt = "n",
            xlab = "Cluster",
            ylab = "Proporción",
            main = paste("Distribución de", v))

    axis(1,
         at = 1:length(levels(c3)),
         labels = levels(c3))

    legend("topright",
           legend = rownames(prop),
           col = 1:nrow(prop),
           lty = 1,
           cex = 0.7)
  }
}

```







